.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 2010-11-07
.Dt watch 1
.Os Darwin
.Sh NAME
.Nm watch
.\" Use .Nm macro to designate other names for the documented program.
.Nd A tool to monitor file system events at a given path
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl r Ar depth
[path path2 ...]
.Sh DESCRIPTION
.Nm
monitors filesystem events and prints out activity.
The following options are available:
.Bl -tag -width -indent
.It Fl h
Displays the usage
.It Fl r Ar depth
The maximum depth in the filesystem heiarchy to monitor
.It Fl v
Prints the version
.El
.Sh AUTHOR
.An Chris R. Cunningham